version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: calendarly
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: buildo/h2database
    container_name: h2-db
    ports:
      - "1521:1521"
      - "81:81"
    environment:
      - H2_OPTIONS=-tcp -tcpAllowOthers
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
